

# This file was *autogenerated* from the file truth.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_191 = Integer(191)
from sage.all import *

a = _sage_const_1 
b = _sage_const_1 
p = _sage_const_191 

if len(sys.argv) != 4:
    print('need 3 arguments [a,b,prime]')
    exit()

a = Integer(sys.argv[1])
b = Integer(sys.argv[2])
p = Integer(sys.argv[3])


curve = EllipticCurve(GF(p),[a,b])
print(curve.cardinality())

